### ISSUE TITLE
Using env vars in plan.yml

### ISSUE THREAD

**Issue by ol1s** [zaproxy/action-af#13]
I have an environment variable `BASE_URL` that is set in my github runner, how can I use this var in my plan.yml?

For example, the following example does not work:

```
// workflow.yml
- uses: zaproxy/action-af@v0.1.0
  with:
    plan: .zap/plan.yml
    docker_env_vars: |
      BASE_URL
```

```
// plan.yml
env:
  contexts:
    - name: Context 1
      urls:
        - ${BASE_URL}
```

```
Automation plan failures:
	Invalid URL: ${BASE_URL}
Automation plan warnings:
	Variable BASE_URL used but not specified
```

**Comment by thc202** [comment]
That's mentioned in https://github.com/zaproxy/action-af?tab=readme-ov-file#docker_env_vars

---
### `docker_env_vars`

**Optional** The names of the environment variables that should be passed to the Docker container for use in the plan, e.g.:
```yaml
docker_env_vars: |
  MY_TARGET_URL
  MY_USER_NAME
  MY_USER_PASSWORD
```
See also [Environment variables](#environment-variables).

**Comment by thc202** [comment]
Can you show your whole configuration of the action?

See https://github.com/zaproxy/action-af/blob/c3e6035f3bd8390827dfb0712da1bf1e51d3854d/.github/workflows/check-run.yml#L26-L34

**Comment by ol1s** [comment]
Here is the full job configuration:

```
jobs:
  check-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "BASE_URL=https://example.com" >> $GITHUB_ENV
      - uses: zaproxy/action-af@v0.1.0
        with:
          plan: .zap/plan.yml
          docker_env_vars: |
            BASE_URL
```

From the github logs I can see the env var is there in the runner:

```
Warning: Unexpected input(s) 'docker_env_vars', valid inputs are ['plan', 'docker_name', 'cmd_options']

Run zaproxy/action-af@v0.1.0
  env:
    BASE_URL: https://example.com
```
